[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc.workspace = true

serde.workspace = true
serde_json.workspace = true

log.workspace = true

strum.workspace = true
strum_macros.workspace = true