# mwha2mqtt example config
#
# Defaults are shown commented out.
#
# Settings of type Duration:
# Durations are defined as a TOML string with format: "<value><suffix>".
# Whitespace may be included between "value" and "suffix".
# Various suffixes are supported, including "s"/"sec"/"second" and "ms"/"msec" (for milliseconds).
# (a full list of supported suffixes is here: https://docs.rs/humantime/latest/humantime/fn.parse_duration.html)

[logging]

[port.serial]
# The serial port device file path (i.e., /dev/ttyUSB0).
device = "/dev/ttyUSB1"

# The serial port baud rate.
# One of 9600, 19200, 38400, 57600, 115200, 230400 or "auto" can be specified.
# "auto" will detect the current baud rate. 
# Values other that 9600 (amp power-on default) or "auto" require the amp to already be configured to use the specified baud before mwha2mqttd starts.
# You probably want "auto".
#baud = "auto"

# Whether to adjust the amp and port baud rates once connected.
# One of "off", 9600, 19200, 38400, 57600, 115200, 230400 or "max" can be specified.
# "off" will disable baudrate adjustment (the specified/detected baud rate will be used (see "baud")).
# "max" is equivalent to 230400.
#adjust_baud =  "off"

# Whether to reset the device and port baud rate to the original (detected) rate on exit.
#reset_baud = true

# Serial read timeout
#read_timeout = 1 sec


#[port.tcp]
#url = "raw://localhost:88"

# network read timeout
#read_timeout = 1



[mqtt]
# URL of the MQTT server.
# mqtt[s]://[username[:password]@]host[:port]/<topic-prefix>
#
# 'mqtt' and 'mqtts' schemes are supported, for unencrypted and TLS-encrypted MQTT connections respectivly.
# Websockets are currently not supported.
# 
# A port number can be specified to use something other than the default (1883 for 'mqtt', 8883 for 'mqtts').
# A port number cannot be specified if srv_lookup is true (the port number comes from the SRV record).
# 
# A username/password can be specified if required by the server.
#
# The URL path, if present, is used as a prefix to all topic name, with the folowing caveats:
# - Trailing slashes aren't added automatically.
#     Typically the prefix should end with a '/' to act as a namespace so that single-level wildcard subscriptions ('+") work as expected.
# - The first leading '/' is always removed (MQTT topics don't typically begin with '/').
#     Start the path with '//' to have the perfix start with '/' (e.g. '//mwah/' means a prefix of '/mwha/').
# If no path is specified (i.e. no '/' is present after the host/port) the default prefix of 'mwha/' will be used.
# Use '/' to mean no prefix (which is probably not what you want).
# 
# Various query parameters may be specified to alter the MQTT connection settings:
# - 'client_id': string, set a custom client id (default "mwha2mqttd")
# - 'keep_alive_secs': int, number of seconds after which client should ping the broker if there is no other data exchange
# (see the rumqttc MqttOptions documentation for more)

#url = "mqtt://localhost"  # mqtt broker on localhost, default mqtt port, default topic prefix of 'mwha/'.
#url = "mqtt://localhost/my_mwha/"  # mqtt broker on localhost, default mqtt port, topic prefix of 'my_mwha/'.
#url = "mqtt://example.com/mwha/"  # when combined with srv_lookup, will look for a _mqtt._tcp.example.com SRV record.
url = "mqtt://localhost"

# Whether to perform a DNS query for a SRV record containing the details of an MQTT server on a domain.
# When true the host in the MQTT URL is interpreted as a domain, and a DNS query is made against that domain for a SRV record of type
# _mqtt._tcp ('mqtt' scheme) or _secure-mqtt._tcp ('mqtts' scheme).
# TODO: support for this is currently not implemented
srv_lookup = false


# The following paths may start with "$CREDENTIALS_DIRECTORY" to reference certificate/private key files
# managed by systemd's credentials feature (see https://systemd.io/CREDENTIALS/ for details)

# Path to a file of concatenated CA certificates (in PEM format).
# Only used for mqtts connections.
# Leave unset to use the system default CA.
ca_certs = "foo.pem"

# Path to the client certificate chain file (in PEM format).
# If specified, enables client certificate authentication.
# Only used for mqtts connections.
# Should also contain CA certificates needed to establish the chain of trust for the client certificate's authenticity.
#client_certs = "/path/to/client_pub.pem"

# Path to the client pkcs8 private key (in PEM format).
# If unset, the private key will be loaded from client_cert.
# Password protected private keys are currently not supported.
# Only used for mqtts connections.
#client_key = "/path/to/client.pem"

[amp]
# The interval between each poll to the amp for zone status information.
# Lower values reduce the delay between adjusting zone attributes via physical keypads and MQTT clients receiving these
# updates, but will result in increased serial traffic and more frequent MQTT messages being sent when keypads are used.
# mwha2mqttd does not publish zone attributes that have not changed since the last publish.
poll_interval = "100 ms"

# Amplifier metatdata.
# This data is optional and arbitrary, but can be customized so that clients (such as mwhactl, mwhamixer and mwha-homekit)
# display the right values.
#manufacturer = "Monoprice"
#model = "MPR-6ZHMAUT"
#serial = "123"


[amp.sources]
# Source config.
# A table of source ids to their names and settings.
# Valid source ids are 1 through 6 (inclusive).
# The value for each entry may either be a (inline) table or string.
# If a string is specified that string is used as the source name.
# Each source has the following attributes:
# - 'name': string, the source name
# - 'enabled': bool, source enable state.
#       Clients may choose to respect this value and hide and/or prevent the selection of a disabled source.
#       This setting does not prevent changing a zones' source to a disabled sources via MQTT, the zone keypads or
#       the hardware PA trigger (which switches all zones to source 1 temporarily).
# Sources default to a name of "Source 𝘯" (where 𝘯 is the source number), if left unspecified.
# Sources default to enabled.

1 = "Public Announcement"
2 = "Living Room TV ARC"
# 3 = "Master Bedroom TV ARC"
# 4 = { name = "AirPlay", enabled = false }
# 5 = "Main PC HDMI"
# 6 = "Rain Machine"


[amp.zones]
# Zone config.
# A table of zone ids to their names.
# Zones not listed will not report status or accept adjustments via MQTT.
#
# A zone id is a numerical 2-digit zone identifier in the format "AZ".
# The first digit "A" is the amplifier number, and valid values are 1 through 3 (inclusive), or 0 (see below).
# The second digit "Z" is the zone number on amplifier "A", and valid values are 1 through 6 (inclusive), or 0 (see below).
#
# "A" should always be 1 or 0 unless you have multiple amps connected via the "expansion connector" ribbon cable.
#
# Zone IDs refer to physical zones unless their ID contains a 0 which instead refers to a virtual zone.
#
# ID 00 is a virtual zone representing all zones (aka "the system").
# No status will be reported for this zone. However, adjustments sent to this zone will adjust all zones on all amps inclduing
# amps and zones not listed in this config.
#
# IDs 10, 20, and 30 are virtual zones representing all zones on amp 1, 2 and 3 (respectively).
# No status will be reported for these zones. However, adjustments sent to these zones will adjust all zones on the respecive amp (amp id A)
# including zones on the amp not listed in this config.
#
# Valid zone ids are:
# 11 through 16: Physical zones on amp 1 ["Master"].
# 21 through 26: Physical zones on amp 2 ["Slave 1"].
# 31 through 36: Physical zones on amp 3 ["Slave 2"].
# 00: Virtual "system" zone, adjusts all zones, no status updates.
# 10: Virtual amp 1 zone, adjusts all zones on amp 1, no status updates.
# 20: Virtual amp 2 zone, adjusts all zones on amp 2, no status updates.
# 30: Virtual amp 3 zone, adjusts all zones on amp 3, no status updates.

00 = "Whole Home Audio"
10 = "Master Amp"
11 = "Study"
12 = "Living Room"
13 = "Alfresco"
# 14 = "Master Bedroom"
# 15 = "Guest Bedroom"
# 16 = "Office"