[package]
name = "mwhacli"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

client = { path = "../client" }

anyhow.workspace = true

url.workspace = true

rumqttc.workspace = true

simplelog = "0.12.1"